[project]
name = "thedeepsearch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "joblib>=1.4.2",
    "pydantic>=2.10.6",
    "tqdm>=4.67.1",
    "typer>=0.15.1",
]
